services:
  postgres:
    image: postgres:17
    container_name: postgres_dw

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dw_projeto

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "dw_projeto"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 12s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dw

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - postgres

  etl_app:
    build: .

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
